/*
 Source Catalog        : schforce
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 150004 (150004)
 File Encoding         : 65001

 Date: 07/03/2024 10:14:27
*/


-- ----------------------------
-- Table structure for attendance_lesson
-- ----------------------------
DROP TABLE IF EXISTS "public"."attendance_lesson";
CREATE TABLE "public"."attendance_lesson" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "teacher_user_id" int4,
  "lesson_schedule_id" int4
)
;

-- ----------------------------
-- Records of attendance_lesson
-- ----------------------------
INSERT INTO "public"."attendance_lesson" VALUES (2, '2024-03-07 08:21:03.4', '2024-03-07 08:21:03.4', 1, 1, 'ACTIVE', 1, 4);
INSERT INTO "public"."attendance_lesson" VALUES (3, '2024-03-07 08:23:04.15', '2024-03-07 08:23:04.15', 1, 1, 'ACTIVE', 1, 4);

-- ----------------------------
-- Table structure for attendance_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."attendance_main";
CREATE TABLE "public"."attendance_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "user_id" int4,
  "clock_in_server" timestamp(6),
  "clock_out_server" timestamp(6),
  "lat_in" numeric,
  "lon_in" numeric,
  "clock_in_client" timestamp(6),
  "clock_out_client" timestamp(6),
  "lat_out" numeric,
  "lon_out" numeric,
  "attendance_lesson_id" int4
)
;

-- ----------------------------
-- Records of attendance_main
-- ----------------------------
INSERT INTO "public"."attendance_main" VALUES (11, '2024-03-07 08:20:23.571', '2024-03-07 08:20:23.571', 1, 1, 'ACTIVE', 1, '2024-03-07 08:20:23.57', NULL, NULL, NULL, '2024-03-07 08:20:23', NULL, NULL, NULL, NULL);
INSERT INTO "public"."attendance_main" VALUES (16, '2024-03-07 08:23:04.178', '2024-03-07 08:23:04.178', 1, 1, 'ACTIVE', 3, '2024-03-07 08:23:04.164', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO "public"."attendance_main" VALUES (17, '2024-03-07 08:23:04.184', '2024-03-07 08:23:04.184', 1, 1, 'ACTIVE', 6, '2024-03-07 08:23:04.164', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
INSERT INTO "public"."attendance_main" VALUES (18, '2024-03-07 08:23:04.192', '2024-03-07 08:23:04.192', 1, 1, 'ACTIVE', 5, '2024-03-07 08:23:04.164', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);

-- ----------------------------
-- Table structure for file_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."file_main";
CREATE TABLE "public"."file_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "table_id" int4,
  "type" varchar(20) COLLATE "pg_catalog"."default",
  "path" varchar(500) COLLATE "pg_catalog"."default",
  "upload_user_id" int4
)
;

-- ----------------------------
-- Records of file_main
-- ----------------------------

-- ----------------------------
-- Table structure for lesson_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."lesson_main";
CREATE TABLE "public"."lesson_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "name" varchar(50) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of lesson_main
-- ----------------------------
INSERT INTO "public"."lesson_main" VALUES (1, NULL, NULL, 1, NULL, 'ACTIVE', 'Matematika');
INSERT INTO "public"."lesson_main" VALUES (2, NULL, NULL, 1, NULL, 'ACTIVE', 'Bhs. Indonesia');
INSERT INTO "public"."lesson_main" VALUES (3, NULL, NULL, 1, NULL, 'ACTIVE', 'IPA');
INSERT INTO "public"."lesson_main" VALUES (4, NULL, NULL, 1, NULL, 'ACTIVE', 'IPS');

-- ----------------------------
-- Table structure for lesson_schedule
-- ----------------------------
DROP TABLE IF EXISTS "public"."lesson_schedule";
CREATE TABLE "public"."lesson_schedule" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "lesson_teacher_id" int4,
  "day" varchar(20) COLLATE "pg_catalog"."default",
  "start_time" int4,
  "end_time" int4,
  "class_id" int4
)
;

-- ----------------------------
-- Records of lesson_schedule
-- ----------------------------
INSERT INTO "public"."lesson_schedule" VALUES (1, NULL, NULL, 1, NULL, 'ACTIVE', 1, 'MONDAY', 800, 1000, 1);
INSERT INTO "public"."lesson_schedule" VALUES (2, NULL, NULL, 1, NULL, 'ACTIVE', 2, 'TUESDAY', 800, 1000, 1);
INSERT INTO "public"."lesson_schedule" VALUES (3, NULL, NULL, 1, NULL, 'ACTIVE', 3, 'WEDNESDAY', 800, 1000, 1);
INSERT INTO "public"."lesson_schedule" VALUES (4, NULL, NULL, 1, NULL, 'ACTIVE', 4, 'THURSDAY', 800, 1000, 1);
INSERT INTO "public"."lesson_schedule" VALUES (5, NULL, NULL, 1, NULL, 'ACTIVE', 1, 'FRIDAY', 800, 1000, 1);
INSERT INTO "public"."lesson_schedule" VALUES (6, NULL, NULL, 1, NULL, 'ACTIVE', 2, 'SATURDAY', 800, 1000, 1);

-- ----------------------------
-- Table structure for lesson_teacher
-- ----------------------------
DROP TABLE IF EXISTS "public"."lesson_teacher";
CREATE TABLE "public"."lesson_teacher" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "teacher_user_id" int4,
  "lesson_id" int4
)
;

-- ----------------------------
-- Records of lesson_teacher
-- ----------------------------
INSERT INTO "public"."lesson_teacher" VALUES (1, NULL, NULL, 1, NULL, 'ACTIVE', 1, 1);
INSERT INTO "public"."lesson_teacher" VALUES (2, NULL, NULL, 1, NULL, 'ACTIVE', 1, 2);
INSERT INTO "public"."lesson_teacher" VALUES (3, NULL, NULL, 1, NULL, 'ACTIVE', 1, 3);
INSERT INTO "public"."lesson_teacher" VALUES (4, NULL, NULL, 1, NULL, 'ACTIVE', 1, 4);

-- ----------------------------
-- Table structure for mock_init
-- ----------------------------
DROP TABLE IF EXISTS "public"."mock_init";
CREATE TABLE "public"."mock_init" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of mock_init
-- ----------------------------

-- ----------------------------
-- Table structure for user_class_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_class_main";
CREATE TABLE "public"."user_class_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "name" varchar(50) COLLATE "pg_catalog"."default",
  "group_id" int4
)
;

-- ----------------------------
-- Records of user_class_main
-- ----------------------------
INSERT INTO "public"."user_class_main" VALUES (1, '2024-02-28 00:00:00', '2024-02-28 00:00:00', NULL, NULL, 'ACTIVE', 'Kelas 1', 1);

-- ----------------------------
-- Table structure for user_corporate_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_corporate_main";
CREATE TABLE "public"."user_corporate_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "name" varchar(50) COLLATE "pg_catalog"."default",
  "code" varchar(50) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of user_corporate_main
-- ----------------------------
INSERT INTO "public"."user_corporate_main" VALUES (1, '2024-02-28 00:00:00', '2024-02-28 00:00:00', NULL, NULL, 'ACTIVE', 'Sekolah Bahagia 1', '240001');

-- ----------------------------
-- Table structure for user_group_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_group_main";
CREATE TABLE "public"."user_group_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "name" varchar(50) COLLATE "pg_catalog"."default",
  "description" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of user_group_main
-- ----------------------------
INSERT INTO "public"."user_group_main" VALUES (1, '2024-02-28 00:00:00', '2024-02-28 00:00:00', NULL, NULL, 'ACTIVE', 'Grup Siang', 'Masuk Siang');

-- ----------------------------
-- Table structure for user_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_main";
CREATE TABLE "public"."user_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "username" varchar(50) COLLATE "pg_catalog"."default",
  "email" varchar(50) COLLATE "pg_catalog"."default",
  "password" varchar(255) COLLATE "pg_catalog"."default",
  "user_type" varchar(20) COLLATE "pg_catalog"."default",
  "full_name" varchar(50) COLLATE "pg_catalog"."default",
  "dob" timestamp(6),
  "pob" varchar(50) COLLATE "pg_catalog"."default",
  "phone" varchar(20) COLLATE "pg_catalog"."default",
  "gender" varchar(20) COLLATE "pg_catalog"."default",
  "level_class_id" int4,
  "join_date" timestamp(6),
  "guardian_user_id" int4,
  "prev_data_id" int4,
  "code" varchar(50) COLLATE "pg_catalog"."default",
  "corporate_id" int4,
  "already_login" bool
)
;

-- ----------------------------
-- Records of user_main
-- ----------------------------
INSERT INTO "public"."user_main" VALUES (1, '2024-02-27 18:00:27.491', '2024-02-27 18:00:27.491', NULL, NULL, 'ACTIVE', 'root', 'root@mail.com', '$2a$10$sVHJqlHh82HPOIzRCY/NtO/y4h9US.BCulx/LG7RoZazLe2cigaP6', 'TEACHER', 'Guru Root', NULL, NULL, NULL, 'MALE', NULL, NULL, NULL, NULL, NULL, 1, 't');
INSERT INTO "public"."user_main" VALUES (2, '2024-02-29 08:36:13.513', '2024-02-29 08:36:13.513', 1, 1, 'ACTIVE', 'nunu', NULL, '59dovkrj', 'GUARDIAN_STUDENT', 'Ibu Nunu', NULL, NULL, '081234', 'FEMALE', NULL, NULL, NULL, NULL, NULL, 1, NULL);
INSERT INTO "public"."user_main" VALUES (3, '2024-02-29 08:36:13.525', '2024-02-29 08:36:13.525', 1, 1, 'ACTIVE', 'ana', NULL, '59dovkrj', 'STUDENT', 'Ana', '2010-10-10 00:00:00', 'bdg', '08123', 'FEMALE', 1, '2024-02-29 08:36:13.499', 2, NULL, '240001', 1, NULL);
INSERT INTO "public"."user_main" VALUES (4, '2024-02-29 08:36:13.525', '2024-02-29 08:36:13.525', 1, NULL, 'ACTIVE', 'anu', NULL, '59dovkrj', 'STUDENT', 'Anu', '2010-10-10 00:00:00', 'bdg', '08123', 'MALE', 1, '2024-02-29 08:36:13.499', 2, NULL, '240002', 1, NULL);
INSERT INTO "public"."user_main" VALUES (6, '2024-02-29 08:36:13.525', '2024-02-29 08:36:13.525', 1, NULL, 'ACTIVE', 'ane', NULL, '59dovkrj', 'STUDENT', 'Ane', '2010-10-10 00:00:00', 'bdg', '08123', 'FEMALE', 1, '2024-02-29 08:36:13.499', 2, NULL, '240003', 1, NULL);
INSERT INTO "public"."user_main" VALUES (5, '2024-02-29 08:36:13.525', '2024-02-29 08:36:13.525', 1, NULL, 'ACTIVE', 'ano', NULL, '59dovkrj', 'STUDENT', 'Ano', '2010-10-10 00:00:00', 'bdg', '08123', 'MALE', 1, '2024-02-29 08:36:13.499', 2, NULL, '240004', 1, NULL);
INSERT INTO "public"."user_main" VALUES (7, '2024-03-07 10:04:40.219', '2024-03-07 10:04:40.219', 1, 1, 'ACTIVE', 'wali.songong', NULL, '57zzktj2', 'GUARDIAN_STUDENT', 'wali songong', NULL, NULL, '089999', 'MALE', NULL, NULL, NULL, NULL, NULL, 1, NULL);
INSERT INTO "public"."user_main" VALUES (8, '2024-03-07 10:04:40.248', '2024-03-07 10:04:40.248', 1, 1, 'ACTIVE', 'wawa', NULL, '57zzktj2', 'STUDENT', 'wawa', '2022-02-02 00:00:00', 'jkt', '08123333', 'MALE', 1, '2024-03-07 10:04:40.176', 7, NULL, NULL, 1, NULL);

-- ----------------------------
-- Table structure for user_menu
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_menu";
CREATE TABLE "public"."user_menu" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "user_id" int4,
  "name" varchar(50) COLLATE "pg_catalog"."default",
  "display_name" varchar(50) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of user_menu
-- ----------------------------

-- ----------------------------
-- Table structure for user_session
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_session";
CREATE TABLE "public"."user_session" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20) COLLATE "pg_catalog"."default",
  "user_id" int4,
  "expired_date" timestamp(6)
)
;

-- ----------------------------
-- Records of user_session
-- ----------------------------
INSERT INTO "public"."user_session" VALUES (1, '2024-02-29 08:31:59.174', '2024-02-29 08:31:59.174', 1, 1, 'ACTIVE', 1, '2024-02-29 13:31:59.141');
INSERT INTO "public"."user_session" VALUES (2, '2024-02-29 08:33:24.95', '2024-02-29 08:33:24.95', 2, 2, 'ACTIVE', 2, '2024-02-29 13:33:24.946');
INSERT INTO "public"."user_session" VALUES (3, '2024-02-29 08:36:07.038', '2024-02-29 08:36:07.038', 100000, 100000, 'ACTIVE', 100000, '2024-02-29 13:36:07.004');
INSERT INTO "public"."user_session" VALUES (4, '2024-02-29 11:17:38.427', '2024-02-29 11:17:38.427', 1, 1, 'ACTIVE', 1, '2024-02-29 16:17:38.396');
INSERT INTO "public"."user_session" VALUES (5, '2024-02-29 11:20:07.412', '2024-02-29 11:20:07.412', 1, 1, 'ACTIVE', 1, '2024-02-29 16:20:07.407');
INSERT INTO "public"."user_session" VALUES (6, '2024-02-29 11:23:42.262', '2024-02-29 11:23:42.262', 1, 1, 'ACTIVE', 1, '2024-02-29 16:23:42.255');
INSERT INTO "public"."user_session" VALUES (7, '2024-03-06 09:29:21.412', '2024-03-06 09:29:21.412', 1, 1, 'ACTIVE', 1, '2024-03-06 14:29:21.379');
INSERT INTO "public"."user_session" VALUES (8, '2024-03-06 10:10:11.163', '2024-03-06 10:10:11.163', 1, 1, 'ACTIVE', 1, '2024-03-06 15:10:11.158');
INSERT INTO "public"."user_session" VALUES (9, '2024-03-06 10:15:39.74', '2024-03-06 10:15:39.74', 1, 1, 'ACTIVE', 1, '2024-03-06 15:15:39.736');
INSERT INTO "public"."user_session" VALUES (10, '2024-03-06 10:19:25.351', '2024-03-06 10:19:25.351', 1, 1, 'ACTIVE', 1, '2024-03-06 15:19:25.347');
INSERT INTO "public"."user_session" VALUES (11, '2024-03-06 10:20:15.779', '2024-03-06 10:20:15.779', 1, 1, 'ACTIVE', 1, '2024-03-06 15:20:15.775');
INSERT INTO "public"."user_session" VALUES (12, '2024-03-06 10:21:02.823', '2024-03-06 10:21:02.823', 1, 1, 'ACTIVE', 1, '2024-03-06 15:21:02.819');
INSERT INTO "public"."user_session" VALUES (13, '2024-03-06 10:31:07.295', '2024-03-06 10:31:07.295', 1, 1, 'ACTIVE', 1, '2024-03-06 15:31:07.29');
INSERT INTO "public"."user_session" VALUES (14, '2024-03-06 10:31:17.998', '2024-03-06 10:31:17.998', 1, 1, 'ACTIVE', 1, '2024-03-06 15:31:17.986');
INSERT INTO "public"."user_session" VALUES (15, '2024-03-06 10:33:24.775', '2024-03-06 10:33:24.775', 1, 1, 'ACTIVE', 1, '2024-03-06 15:33:24.77');
INSERT INTO "public"."user_session" VALUES (16, '2024-03-06 11:09:56.18', '2024-03-06 11:09:56.18', 1, 1, 'ACTIVE', 1, '2024-03-06 16:09:56.176');
INSERT INTO "public"."user_session" VALUES (17, '2024-03-06 11:44:15.632', '2024-03-06 11:44:15.632', 1, 1, 'ACTIVE', 1, '2024-03-06 16:44:15.621');
INSERT INTO "public"."user_session" VALUES (18, '2024-03-06 11:47:23.379', '2024-03-06 11:47:23.379', 1, 1, 'ACTIVE', 1, '2024-03-06 16:47:23.364');
INSERT INTO "public"."user_session" VALUES (19, '2024-03-06 11:49:02.751', '2024-03-06 11:49:02.751', 1, 1, 'ACTIVE', 1, '2024-03-06 16:49:02.746');
INSERT INTO "public"."user_session" VALUES (20, '2024-03-06 11:58:37.035', '2024-03-06 11:58:37.035', 1, 1, 'ACTIVE', 1, '2024-03-06 16:58:37.031');
INSERT INTO "public"."user_session" VALUES (21, '2024-03-06 12:51:38.35', '2024-03-06 12:51:38.35', 1, 1, 'ACTIVE', 1, '2024-03-06 17:51:38.327');
INSERT INTO "public"."user_session" VALUES (22, '2024-03-06 13:56:45.401', '2024-03-06 13:56:45.401', 1, 1, 'ACTIVE', 1, '2024-03-06 18:56:45.395');
INSERT INTO "public"."user_session" VALUES (23, '2024-03-06 14:08:22.06', '2024-03-06 14:08:22.06', 1, 1, 'ACTIVE', 1, '2024-03-06 19:08:22.053');
INSERT INTO "public"."user_session" VALUES (24, '2024-03-06 14:09:54.193', '2024-03-06 14:09:54.193', 1, 1, 'ACTIVE', 1, '2024-03-06 19:09:54.176');
INSERT INTO "public"."user_session" VALUES (25, '2024-03-06 14:10:40.385', '2024-03-06 14:10:40.385', 1, 1, 'ACTIVE', 1, '2024-03-06 19:10:40.374');
INSERT INTO "public"."user_session" VALUES (26, '2024-03-06 14:11:31.352', '2024-03-06 14:11:31.352', 1, 1, 'ACTIVE', 1, '2024-03-06 19:11:31.345');
INSERT INTO "public"."user_session" VALUES (27, '2024-03-06 14:12:17.262', '2024-03-06 14:12:17.262', 1, 1, 'ACTIVE', 1, '2024-03-06 19:12:17.256');
INSERT INTO "public"."user_session" VALUES (28, '2024-03-06 14:12:54.946', '2024-03-06 14:12:54.946', 1, 1, 'ACTIVE', 1, '2024-03-06 19:12:54.927');
INSERT INTO "public"."user_session" VALUES (29, '2024-03-06 14:13:44.598', '2024-03-06 14:13:44.598', 1, 1, 'ACTIVE', 1, '2024-03-06 19:13:44.578');
INSERT INTO "public"."user_session" VALUES (30, '2024-03-06 14:16:45.271', '2024-03-06 14:16:45.271', 1, 1, 'ACTIVE', 1, '2024-03-06 19:16:45.255');
INSERT INTO "public"."user_session" VALUES (31, '2024-03-06 14:20:08.565', '2024-03-06 14:20:08.565', 1, 1, 'ACTIVE', 1, '2024-03-06 19:20:08.558');
INSERT INTO "public"."user_session" VALUES (32, '2024-03-06 14:22:35.146', '2024-03-06 14:22:35.146', 1, 1, 'ACTIVE', 1, '2024-03-06 19:22:35.13');
INSERT INTO "public"."user_session" VALUES (33, '2024-03-06 14:23:49.119', '2024-03-06 14:23:49.119', 1, 1, 'ACTIVE', 1, '2024-03-06 19:23:49.114');
INSERT INTO "public"."user_session" VALUES (34, '2024-03-06 14:30:00.246', '2024-03-06 14:30:00.246', 1, 1, 'ACTIVE', 1, '2024-03-06 19:30:00.242');
INSERT INTO "public"."user_session" VALUES (35, '2024-03-06 14:32:19.004', '2024-03-06 14:32:19.004', 1, 1, 'ACTIVE', 1, '2024-03-06 19:32:19');
INSERT INTO "public"."user_session" VALUES (36, '2024-03-06 14:53:47.13', '2024-03-06 14:53:47.13', 1, 1, 'ACTIVE', 1, '2024-03-06 19:53:47.12');
INSERT INTO "public"."user_session" VALUES (37, '2024-03-06 14:58:19.602', '2024-03-06 14:58:19.602', 1, 1, 'ACTIVE', 1, '2024-03-06 19:58:19.591');
INSERT INTO "public"."user_session" VALUES (38, '2024-03-06 15:00:36.563', '2024-03-06 15:00:36.563', 1, 1, 'ACTIVE', 1, '2024-03-06 20:00:36.559');
INSERT INTO "public"."user_session" VALUES (39, '2024-03-06 15:01:50.944', '2024-03-06 15:01:50.944', 1, 1, 'ACTIVE', 1, '2024-03-06 20:01:50.93');
INSERT INTO "public"."user_session" VALUES (40, '2024-03-06 15:02:23.949', '2024-03-06 15:02:23.949', 1, 1, 'ACTIVE', 1, '2024-03-06 20:02:23.935');
INSERT INTO "public"."user_session" VALUES (41, '2024-03-06 15:04:31.116', '2024-03-06 15:04:31.116', 1, 1, 'ACTIVE', 1, '2024-03-06 20:04:31.105');
INSERT INTO "public"."user_session" VALUES (42, '2024-03-06 15:08:18.755', '2024-03-06 15:08:18.755', 1, 1, 'ACTIVE', 1, '2024-03-06 20:08:18.748');
INSERT INTO "public"."user_session" VALUES (43, '2024-03-06 15:12:59.144', '2024-03-06 15:12:59.144', 1, 1, 'ACTIVE', 1, '2024-03-06 20:12:59.139');
INSERT INTO "public"."user_session" VALUES (44, '2024-03-06 15:14:12.521', '2024-03-06 15:14:12.521', 1, 1, 'ACTIVE', 1, '2024-03-06 20:14:12.517');
INSERT INTO "public"."user_session" VALUES (45, '2024-03-06 15:16:24.592', '2024-03-06 15:16:24.592', 1, 1, 'ACTIVE', 1, '2024-03-06 20:16:24.576');
INSERT INTO "public"."user_session" VALUES (46, '2024-03-06 15:18:15.906', '2024-03-06 15:18:15.906', 1, 1, 'ACTIVE', 1, '2024-03-06 20:18:15.902');
INSERT INTO "public"."user_session" VALUES (47, '2024-03-06 15:20:32.895', '2024-03-06 15:20:32.895', 1, 1, 'ACTIVE', 1, '2024-03-06 20:20:32.893');
INSERT INTO "public"."user_session" VALUES (48, '2024-03-06 15:22:53.815', '2024-03-06 15:22:53.815', 1, 1, 'ACTIVE', 1, '2024-03-06 20:22:53.811');
INSERT INTO "public"."user_session" VALUES (49, '2024-03-06 15:26:12.34', '2024-03-06 15:26:12.34', 1, 1, 'ACTIVE', 1, '2024-03-06 20:26:12.331');
INSERT INTO "public"."user_session" VALUES (50, '2024-03-06 15:30:21.467', '2024-03-06 15:30:21.468', 1, 1, 'ACTIVE', 1, '2024-03-06 20:30:21.463');
INSERT INTO "public"."user_session" VALUES (51, '2024-03-06 15:32:55.169', '2024-03-06 15:32:55.169', 1, 1, 'ACTIVE', 1, '2024-03-06 20:32:55.152');
INSERT INTO "public"."user_session" VALUES (52, '2024-03-06 15:36:20.26', '2024-03-06 15:36:20.26', 1, 1, 'ACTIVE', 1, '2024-03-06 20:36:20.256');
INSERT INTO "public"."user_session" VALUES (53, '2024-03-06 15:48:37.218', '2024-03-06 15:48:37.218', 1, 1, 'ACTIVE', 1, '2024-03-06 20:48:37.199');
INSERT INTO "public"."user_session" VALUES (54, '2024-03-06 15:51:23.809', '2024-03-06 15:51:23.809', 1, 1, 'ACTIVE', 1, '2024-03-06 20:51:23.794');
INSERT INTO "public"."user_session" VALUES (55, '2024-03-06 16:02:08.817', '2024-03-06 16:02:08.817', 1, 1, 'ACTIVE', 1, '2024-03-06 21:02:08.814');
INSERT INTO "public"."user_session" VALUES (56, '2024-03-06 16:03:21.008', '2024-03-06 16:03:21.008', 1, 1, 'ACTIVE', 1, '2024-03-06 21:03:21.005');
INSERT INTO "public"."user_session" VALUES (57, '2024-03-06 16:03:59.415', '2024-03-06 16:03:59.415', 1, 1, 'ACTIVE', 1, '2024-03-06 21:03:59.412');
INSERT INTO "public"."user_session" VALUES (58, '2024-03-06 16:04:48.284', '2024-03-06 16:04:48.284', 1, 1, 'ACTIVE', 1, '2024-03-06 21:04:48.271');
INSERT INTO "public"."user_session" VALUES (59, '2024-03-06 16:07:02.57', '2024-03-06 16:07:02.57', 1, 1, 'ACTIVE', 1, '2024-03-06 21:07:02.567');
INSERT INTO "public"."user_session" VALUES (60, '2024-03-06 16:20:03.527', '2024-03-06 16:20:03.527', 1, 1, 'ACTIVE', 1, '2024-03-06 21:20:03.511');
INSERT INTO "public"."user_session" VALUES (61, '2024-03-06 16:21:41.25', '2024-03-06 16:21:41.25', 1, 1, 'ACTIVE', 1, '2024-03-06 21:21:41.247');
INSERT INTO "public"."user_session" VALUES (62, '2024-03-06 16:24:22.049', '2024-03-06 16:24:22.049', 1, 1, 'ACTIVE', 1, '2024-03-06 21:24:22.045');
INSERT INTO "public"."user_session" VALUES (63, '2024-03-06 16:25:04.693', '2024-03-06 16:25:04.693', 1, 1, 'ACTIVE', 1, '2024-03-06 21:25:04.69');
INSERT INTO "public"."user_session" VALUES (64, '2024-03-06 16:27:39.731', '2024-03-06 16:27:39.731', 1, 1, 'ACTIVE', 1, '2024-03-06 21:27:39.728');
INSERT INTO "public"."user_session" VALUES (65, '2024-03-06 16:29:50.98', '2024-03-06 16:29:50.98', 1, 1, 'ACTIVE', 1, '2024-03-06 21:29:50.978');
INSERT INTO "public"."user_session" VALUES (66, '2024-03-06 16:33:33.353', '2024-03-06 16:33:33.353', 1, 1, 'ACTIVE', 1, '2024-03-06 21:33:33.349');
INSERT INTO "public"."user_session" VALUES (67, '2024-03-06 16:34:54.693', '2024-03-06 16:34:54.693', 1, 1, 'ACTIVE', 1, '2024-03-06 21:34:54.69');
INSERT INTO "public"."user_session" VALUES (68, '2024-03-06 16:36:17.766', '2024-03-06 16:36:17.766', 1, 1, 'ACTIVE', 1, '2024-03-06 21:36:17.763');
INSERT INTO "public"."user_session" VALUES (69, '2024-03-06 16:37:00.542', '2024-03-06 16:37:00.542', 1, 1, 'ACTIVE', 1, '2024-03-06 21:37:00.54');
INSERT INTO "public"."user_session" VALUES (70, '2024-03-06 16:37:44.059', '2024-03-06 16:37:44.059', 1, 1, 'ACTIVE', 1, '2024-03-06 21:37:44.055');
INSERT INTO "public"."user_session" VALUES (71, '2024-03-06 16:38:45.537', '2024-03-06 16:38:45.537', 1, 1, 'ACTIVE', 1, '2024-03-06 21:38:45.535');
INSERT INTO "public"."user_session" VALUES (72, '2024-03-06 16:40:18.95', '2024-03-06 16:40:18.95', 1, 1, 'ACTIVE', 1, '2024-03-06 21:40:18.946');
INSERT INTO "public"."user_session" VALUES (73, '2024-03-06 16:41:49.381', '2024-03-06 16:41:49.381', 1, 1, 'ACTIVE', 1, '2024-03-06 21:41:49.379');
INSERT INTO "public"."user_session" VALUES (74, '2024-03-06 16:42:59.708', '2024-03-06 16:42:59.708', 1, 1, 'ACTIVE', 1, '2024-03-06 21:42:59.705');
INSERT INTO "public"."user_session" VALUES (75, '2024-03-06 16:44:09.354', '2024-03-06 16:44:09.354', 1, 1, 'ACTIVE', 1, '2024-03-06 21:44:09.34');
INSERT INTO "public"."user_session" VALUES (76, '2024-03-06 16:48:20.86', '2024-03-06 16:48:20.86', 1, 1, 'ACTIVE', 1, '2024-03-06 21:48:20.856');
INSERT INTO "public"."user_session" VALUES (77, '2024-03-06 18:52:08.708', '2024-03-06 18:52:08.708', 1, 1, 'ACTIVE', 1, '2024-03-06 23:52:08.701');
INSERT INTO "public"."user_session" VALUES (78, '2024-03-06 18:54:15.836', '2024-03-06 18:54:15.836', 1, 1, 'ACTIVE', 1, '2024-03-06 23:54:15.826');
INSERT INTO "public"."user_session" VALUES (79, '2024-03-06 19:00:34.259', '2024-03-06 19:00:34.259', 1, 1, 'ACTIVE', 1, '2024-03-07 00:00:34.253');
INSERT INTO "public"."user_session" VALUES (80, '2024-03-06 20:26:30.774', '2024-03-06 20:26:30.774', 1, 1, 'ACTIVE', 1, '2024-03-07 01:26:30.771');
INSERT INTO "public"."user_session" VALUES (81, '2024-03-06 20:41:51.274', '2024-03-06 20:41:51.274', 1, 1, 'ACTIVE', 1, '2024-03-07 01:41:51.27');
INSERT INTO "public"."user_session" VALUES (82, '2024-03-06 20:43:25.748', '2024-03-06 20:43:25.748', 1, 1, 'ACTIVE', 1, '2024-03-07 01:43:25.744');
INSERT INTO "public"."user_session" VALUES (83, '2024-03-06 20:49:01.334', '2024-03-06 20:49:01.334', 1, 1, 'ACTIVE', 1, '2024-03-07 01:49:01.301');
INSERT INTO "public"."user_session" VALUES (84, '2024-03-06 20:52:21.884', '2024-03-06 20:52:21.884', 1, 1, 'ACTIVE', 1, '2024-03-07 01:52:21.879');
INSERT INTO "public"."user_session" VALUES (85, '2024-03-06 20:53:09.05', '2024-03-06 20:53:09.05', 1, 1, 'ACTIVE', 1, '2024-03-07 01:53:09.046');
INSERT INTO "public"."user_session" VALUES (86, '2024-03-06 20:55:00.411', '2024-03-06 20:55:00.411', 1, 1, 'ACTIVE', 1, '2024-03-07 01:55:00.407');
INSERT INTO "public"."user_session" VALUES (87, '2024-03-06 21:04:00.895', '2024-03-06 21:04:00.895', 1, 1, 'ACTIVE', 1, '2024-03-07 02:04:00.89');
INSERT INTO "public"."user_session" VALUES (88, '2024-03-06 21:04:38.297', '2024-03-06 21:04:38.297', 1, 1, 'ACTIVE', 1, '2024-03-07 02:04:38.293');
INSERT INTO "public"."user_session" VALUES (89, '2024-03-06 21:05:15.552', '2024-03-06 21:05:15.552', 1, 1, 'ACTIVE', 1, '2024-03-07 02:05:15.548');
INSERT INTO "public"."user_session" VALUES (90, '2024-03-06 21:05:44.301', '2024-03-06 21:05:44.301', 1, 1, 'ACTIVE', 1, '2024-03-07 02:05:44.297');
INSERT INTO "public"."user_session" VALUES (91, '2024-03-06 21:06:19.824', '2024-03-06 21:06:19.824', 1, 1, 'ACTIVE', 1, '2024-03-07 02:06:19.821');
INSERT INTO "public"."user_session" VALUES (92, '2024-03-07 08:04:59.006', '2024-03-07 08:04:59.006', 1, 1, 'ACTIVE', 1, '2024-03-07 13:04:58.943');
INSERT INTO "public"."user_session" VALUES (93, '2024-03-07 08:16:45.587', '2024-03-07 08:16:45.587', 1, 1, 'ACTIVE', 1, '2024-03-07 13:16:45.579');
INSERT INTO "public"."user_session" VALUES (94, '2024-03-07 08:20:21.656', '2024-03-07 08:20:21.656', 1, 1, 'ACTIVE', 1, '2024-03-07 13:20:21.649');
INSERT INTO "public"."user_session" VALUES (95, '2024-03-07 08:22:44.997', '2024-03-07 08:22:44.997', 1, 1, 'ACTIVE', 1, '2024-03-07 13:22:44.99');
INSERT INTO "public"."user_session" VALUES (96, '2024-03-07 08:27:39.914', '2024-03-07 08:27:39.914', 1, 1, 'ACTIVE', 1, '2024-03-07 13:27:39.9');
INSERT INTO "public"."user_session" VALUES (97, '2024-03-07 08:36:51.439', '2024-03-07 08:36:51.439', 1, 1, 'ACTIVE', 1, '2024-03-07 13:36:51.433');
INSERT INTO "public"."user_session" VALUES (98, '2024-03-07 08:55:41.63', '2024-03-07 08:55:41.63', 1, 1, 'ACTIVE', 1, '2024-03-07 13:55:41.554');
INSERT INTO "public"."user_session" VALUES (99, '2024-03-07 09:05:59.165', '2024-03-07 09:05:59.165', 1, 1, 'ACTIVE', 1, '2024-03-07 14:05:59.133');
INSERT INTO "public"."user_session" VALUES (100, '2024-03-07 09:10:40.412', '2024-03-07 09:10:40.412', 1, 1, 'ACTIVE', 1, '2024-03-07 14:10:40.379');
INSERT INTO "public"."user_session" VALUES (101, '2024-03-07 09:23:12.855', '2024-03-07 09:23:12.855', 1, 1, 'ACTIVE', 1, '2024-03-07 14:23:12.822');
INSERT INTO "public"."user_session" VALUES (102, '2024-03-07 09:25:09.709', '2024-03-07 09:25:09.709', 1, 1, 'ACTIVE', 1, '2024-03-07 14:25:09.702');
INSERT INTO "public"."user_session" VALUES (103, '2024-03-07 09:42:29.83', '2024-03-07 09:42:29.83', 1, 1, 'ACTIVE', 1, '2024-03-07 14:42:29.825');
INSERT INTO "public"."user_session" VALUES (104, '2024-03-07 09:44:28.057', '2024-03-07 09:44:28.057', 1, 1, 'ACTIVE', 1, '2024-03-07 14:44:28.053');
INSERT INTO "public"."user_session" VALUES (105, '2024-03-07 09:45:04.912', '2024-03-07 09:45:04.912', 1, 1, 'ACTIVE', 1, '2024-03-07 14:45:04.907');
INSERT INTO "public"."user_session" VALUES (106, '2024-03-07 09:46:10.79', '2024-03-07 09:46:10.79', 1, 1, 'ACTIVE', 1, '2024-03-07 14:46:10.786');
INSERT INTO "public"."user_session" VALUES (107, '2024-03-07 09:59:00.859', '2024-03-07 09:59:00.859', 1, 1, 'ACTIVE', 1, '2024-03-07 14:59:00.853');
INSERT INTO "public"."user_session" VALUES (108, '2024-03-07 10:02:19.077', '2024-03-07 10:02:19.077', 1, 1, 'ACTIVE', 1, '2024-03-07 15:02:19.07');
INSERT INTO "public"."user_session" VALUES (109, '2024-03-07 10:03:46.388', '2024-03-07 10:03:46.388', 1, 1, 'ACTIVE', 1, '2024-03-07 15:03:46.383');

-- ----------------------------
-- Auto increment value for attendance_lesson
-- ----------------------------
SELECT setval('"public"."mock_init_copy1_id_seq"', 3, true);

-- ----------------------------
-- Primary Key structure for table attendance_lesson
-- ----------------------------
ALTER TABLE "public"."attendance_lesson" ADD CONSTRAINT "mock_init_copy1_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for attendance_main
-- ----------------------------
SELECT setval('"public"."attendance_main_id_seq"', 18, true);

-- ----------------------------
-- Primary Key structure for table attendance_main
-- ----------------------------
ALTER TABLE "public"."attendance_main" ADD CONSTRAINT "attendance_main_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for file_main
-- ----------------------------
SELECT setval('"public"."file_main_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table file_main
-- ----------------------------
ALTER TABLE "public"."file_main" ADD CONSTRAINT "file_main_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for lesson_main
-- ----------------------------
SELECT setval('"public"."lesson_main_id_seq"', 4, true);

-- ----------------------------
-- Primary Key structure for table lesson_main
-- ----------------------------
ALTER TABLE "public"."lesson_main" ADD CONSTRAINT "lesson_main_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for lesson_schedule
-- ----------------------------
SELECT setval('"public"."lesson_schedule_id_seq"', 6, true);

-- ----------------------------
-- Primary Key structure for table lesson_schedule
-- ----------------------------
ALTER TABLE "public"."lesson_schedule" ADD CONSTRAINT "lesson_schedule_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for lesson_teacher
-- ----------------------------
SELECT setval('"public"."lesson_teacher_id_seq"', 4, true);

-- ----------------------------
-- Primary Key structure for table lesson_teacher
-- ----------------------------
ALTER TABLE "public"."lesson_teacher" ADD CONSTRAINT "lesson_teacher_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for mock_init
-- ----------------------------
SELECT setval('"public"."mock_init_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table mock_init
-- ----------------------------
ALTER TABLE "public"."mock_init" ADD CONSTRAINT "mock_init_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for user_class_main
-- ----------------------------
SELECT setval('"public"."user_class_main_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table user_class_main
-- ----------------------------
ALTER TABLE "public"."user_class_main" ADD CONSTRAINT "user_class_main_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for user_corporate_main
-- ----------------------------
SELECT setval('"public"."user_corporate_main_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table user_corporate_main
-- ----------------------------
ALTER TABLE "public"."user_corporate_main" ADD CONSTRAINT "user_corporate_main_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for user_group_main
-- ----------------------------
SELECT setval('"public"."user_group_main_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table user_group_main
-- ----------------------------
ALTER TABLE "public"."user_group_main" ADD CONSTRAINT "user_group_main_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for user_main
-- ----------------------------
SELECT setval('"public"."user_main_id_seq"', 8, true);

-- ----------------------------
-- Primary Key structure for table user_main
-- ----------------------------
ALTER TABLE "public"."user_main" ADD CONSTRAINT "user_main_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for user_menu
-- ----------------------------
SELECT setval('"public"."user_menu_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table user_menu
-- ----------------------------
ALTER TABLE "public"."user_menu" ADD CONSTRAINT "user_menu_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for user_session
-- ----------------------------
SELECT setval('"public"."user_session_id_seq"', 109, true);

-- ----------------------------
-- Primary Key structure for table user_session
-- ----------------------------
ALTER TABLE "public"."user_session" ADD CONSTRAINT "user_session_pkey" PRIMARY KEY ("id");
