-- ----------------------------
-- Table structure for attendance_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."attendance_main";
CREATE TABLE "public"."attendance_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "user_id" int4,
  "clock_in_server" timestamp(6),
  "clock_out_server" timestamp(6),
  "lat_in" numeric,
  "lon_in" numeric,
  "clock_in_client" timestamp(6),
  "clock_out_client" timestamp(6),
  "lat_out" numeric,
  "lon_out" numeric
, PRIMARY KEY ("id"));

-- ----------------------------
-- Table structure for file_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."file_main";
CREATE TABLE "public"."file_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "table_id" int4,
  "type" varchar(20),
  "path" varchar(500),
  "upload_user_id" int4
, PRIMARY KEY ("id"));

-- ----------------------------
-- Records of file_main
-- ----------------------------

-- ----------------------------
-- Table structure for lesson_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."lesson_main";
CREATE TABLE "public"."lesson_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "name" varchar(50)
, PRIMARY KEY ("id"));

-- ----------------------------
-- Records of lesson_main
-- ----------------------------

-- ----------------------------
-- Table structure for lesson_schedule
-- ----------------------------
DROP TABLE IF EXISTS "public"."lesson_schedule";
CREATE TABLE "public"."lesson_schedule" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "lesson_teacher_id" int4,
  "day" varchar(20),
  "start_time" timestamp(6),
  "end_time" timestamp(6),
  "class_id" int4
, PRIMARY KEY ("id"));

-- ----------------------------
-- Records of lesson_schedule
-- ----------------------------

-- ----------------------------
-- Table structure for lesson_teacher
-- ----------------------------
DROP TABLE IF EXISTS "public"."lesson_teacher";
CREATE TABLE "public"."lesson_teacher" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "teacher_user_id" int4,
  "lesson_id" int4
, PRIMARY KEY ("id"));

-- ----------------------------
-- Records of lesson_teacher
-- ----------------------------

-- ----------------------------
-- Table structure for mock_init_2
-- ----------------------------
DROP TABLE IF EXISTS "public"."mock_init";
CREATE TABLE "public"."mock_init" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20)
, PRIMARY KEY ("id"));

-- ----------------------------
-- Records of mock_init_2
-- ----------------------------

-- ----------------------------
-- Table structure for user_class_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_class_main";
CREATE TABLE "public"."user_class_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "name" varchar(50),
  "group_id" int4
, PRIMARY KEY ("id"));

-- ----------------------------
-- Records of user_class_main
-- ----------------------------
INSERT INTO "public"."user_class_main" VALUES (1, '2024-02-28 00:00:00', '2024-02-28 00:00:00', NULL, NULL, 'ACTIVE', 'Kelas 1', 1);

-- ----------------------------
-- Table structure for user_corporate_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_corporate_main";
CREATE TABLE "public"."user_corporate_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "name" varchar(50),
  "code" varchar(50)
, PRIMARY KEY ("id"));

-- ----------------------------
-- Records of user_corporate_main
-- ----------------------------
INSERT INTO "public"."user_corporate_main" VALUES (1, '2024-02-28 00:00:00', '2024-02-28 00:00:00', NULL, NULL, 'ACTIVE', 'Sekolah Bahagia 1', '240001');

-- ----------------------------
-- Table structure for user_group_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_group_main";
CREATE TABLE "public"."user_group_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "name" varchar(50),
  "description" varchar(255)
, PRIMARY KEY ("id"));

-- ----------------------------
-- Records of user_group_main
-- ----------------------------
INSERT INTO "public"."user_group_main" VALUES (1, '2024-02-28 00:00:00', '2024-02-28 00:00:00', NULL, NULL, 'ACTIVE', 'Grup Siang', 'Masuk Siang');

-- ----------------------------
-- Table structure for user_main
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_main";
CREATE TABLE "public"."user_main" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "username" varchar(50),
  "email" varchar(50),
  "password" varchar(255),
  "user_type" varchar(20),
  "full_name" varchar(50),
  "dob" timestamp(6),
  "pob" varchar(50),
  "phone" varchar(20),
  "gender" varchar(20),
  "level_class_id" int4,
  "join_date" timestamp(6),
  "guardian_user_id" int4,
  "prev_data_id" int4,
  "code" varchar(50),
  "corporate_id" int4,
  "already_login" bool
, PRIMARY KEY ("id"));

-- ----------------------------
-- Records of user_main
-- ----------------------------
INSERT INTO "public"."user_main" (
    "created_date",
    "updated_date",
    "created_user_id",
    "updated_user_id",
    "status_data",
    "username",
    "email",
    "password",
    "user_type",
    "full_name",
    "dob",
    "pob",
    "phone",
    "gender",
    "level_class_id",
    "join_date",
    "guardian_user_id",
    "prev_data_id",
    "code",
    "corporate_id",
    "already_login") VALUES ('2024-02-27 18:00:27.491', '2024-02-27 18:00:27.491', NULL, NULL, 'ACTIVE', 'root', 'root@mail.com', '$2a$10$sVHJqlHh82HPOIzRCY/NtO/y4h9US.BCulx/LG7RoZazLe2cigaP6', 'TEACHER', 'Guru Root', NULL, NULL, NULL, 'MALE', NULL, NULL, NULL, NULL, NULL, 1, 't');

-- ----------------------------
-- Table structure for user_menu
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_menu";
CREATE TABLE "public"."user_menu" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "user_id" int4,
  "name" varchar(50),
  "display_name" varchar(50)
, PRIMARY KEY ("id"));

-- ----------------------------
-- Records of user_menu
-- ----------------------------

-- ----------------------------
-- Table structure for user_session
-- ----------------------------
DROP TABLE IF EXISTS "public"."user_session";
CREATE TABLE "public"."user_session" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
  "created_date" timestamp(6),
  "updated_date" timestamp(6),
  "created_user_id" int4,
  "updated_user_id" int4,
  "status_data" varchar(20),
  "user_id" int4,
  "expired_date" timestamp(6)
, PRIMARY KEY ("id"));
